### ISSUE TITLE
The "--only-path" option does not exist. 

### ISSUE THREAD

**Issue by OliverGrimsley** [Wulfheart/pretty-routes#11]
PHP 8.0.3.  Laravel app: (current) 8.40.0.  (shell alias `art` for `php artisan` in below commands)

This is great tool THANK YOU for making it.  Command works without options.  In addition to the issue previously reported re: `str_repeat(): Argument #2 ($times) must be greater than or equal to 0` - which is still present for me in php8... (I get that when I run `art route:pretty --method=POST`)

When I run:

`art route:pretty --only-path=transactions` (to be clear, there is in fact a path `transactions`)

I get `The "--only-path" option does not exist.` 

![Screen Shot 2021-04-29 at 9 34 32 AM](https://user-images.githubusercontent.com/12251451/116559181-260c4600-a8ce-11eb-926f-f4dcef24b887.png)

**Comment by Wulfheart** [comment]
Which package version do you use? Currently this option is merged in master but not released yet.

**Comment by OliverGrimsley** [comment]
> Which package version do you use? Currently this option is merged in master but not released yet.

`"wulfheart/pretty_routes": "^0.1.2"`

**Comment by Wulfheart** [comment]
For a temporary fix change it to `"wulfheart/pretty_routes": "dev-master"`

**Comment by OliverGrimsley** [comment]
Worked!  thx
