### ISSUE TITLE
Lumen compatibility?

### ISSUE THREAD

**Issue by ssi-anik** [Wulfheart/pretty-routes#13]
Is there any plan to support Lumen? Is there any specific reason to start from `^8.x`?

**Comment by Gummibeer** [comment]
There's already support for PHP7.4 added - not yet released.
As the router is one of the biggest differences between Laravel and Lumen it could get a tough task. 🤔

**Comment by Wulfheart** [comment]
Agreed. 
As Taylor Otwell stated that Lumen is feature complete there won't be Lumen support for now. Therefore I will close this issue.
