### ISSUE TITLE
Filtering for route names

### ISSUE THREAD

**Issue by bhushan** [Wulfheart/pretty-routes#15]
What if we have a new custom flag which will show only the routes we want 

—show=tickets 

it will show only routes which has tickets in it. 

If you think its good i can send you a PR.

**Comment by Wulfheart** [comment]
Do you mean the path? Currently `--only-path=tickets` would do the job.

**Comment by bhushan** [comment]
It only checks the uri.. people sometimes search by route name as well .. actually i do it. 

I use ‘php artisan route:list | grep tickets’ for this now. 

This will be nice addition.. we can have more generic name for this flag as it checks for both.

**Comment by Wulfheart** [comment]
Maybe something like `--only-name=foo` and `--except-name=bar` would be the way to go for feature-parity. If you feel you can do it, go for it.

**Comment by bhushan** [comment]
someone already shared the same PR after discussion.. hehe #18

**Comment by Wulfheart** [comment]
With the current release (0.3.0) this functionality is now supported.
