### ISSUE TITLE
Display issue when using more than two methods

### ISSUE THREAD

**Issue by Wulfheart** [Wulfheart/pretty-routes#23]
![grafik](https://user-images.githubusercontent.com/25671390/116709516-09a50200-a9d1-11eb-8cea-ed60cd10da65.png)
https://twitter.com/el_sayed85/status/1387591106804727811?s=20

As you might see there is an issue in the first line: It doesn't align correctly. More information like package version needed.

**Comment by Gummibeer** [comment]
It shouldn't show a warning but move all other lines properly to the right.

**Comment by Wulfheart** [comment]
Closing as the Laravel 9 will support the command natively as per [this PR](https://github.com/laravel/framework/pull/40269).
