### ISSUE TITLE
Add --except-path to config file

### ISSUE THREAD

**Issue by s-patompong** [Wulfheart/pretty-routes#25]
Just a thought here, maybe it'd nice to move the config inside the config file and let the user overwrite them if they explicitly put it in the command.

**Comment by Wulfheart** [comment]
But couldn't this also be achieved via Aliases?
This would require also something like a `--ignore-config` or `--all` option to tell the command to ignore the config if it is desired to display everything. Even though I like this idea I'm not sure if many users would use it.

**Comment by Gummibeer** [comment]
I also prefer composer scripts for such things - for example I have a `composer route:list` script which only lists my application routes.
```bash
"route:list": "@php artisan route:pretty --except-path=nova,horizon,_debugbar,livewire,filament",
```

**Comment by s-patompong** [comment]
That makes sense, I didn't think about Aliases.

Let me close the issue :)

**Comment by Wulfheart** [comment]
> ```shell
> "route:list": "@php artisan route:pretty --except-path=nova,horizon,_debugbar,livewire,filament",
> ```

Nice alias.

**Comment by s-patompong** [comment]
> > ```shell
> > "route:list": "@php artisan route:pretty --except-path=nova,horizon,_debugbar,livewire,filament",
> > ```
> 
> Nice alias.

Very nice, indeed. Already added it to my composer.json file.

@Gummibeer thank you!
