### ISSUE TITLE
Error when running route:pretty (str_repeat(): Argument #2 ($times) must be greater than or equal to 0)

### ISSUE THREAD

**Issue by freekmurze** [Wulfheart/pretty-routes#3]
Thanks for the great package.

I'm getting this error when running the command at https://github.com/spatie/freek.dev

<img width="997" alt="CleanShot 2021-04-28 at 20 06 03" src="https://user-images.githubusercontent.com/483853/116451730-2ae4e180-a85d-11eb-980f-330395170ebf.png">

https://flareapp.io/share/VP6k12x7#F17

**Comment by Wulfheart** [comment]
Thanks for reporting. I will have a look at it.

**Comment by Gummibeer** [comment]
fixed by #2
