### ISSUE TITLE
Option to display controller and method 

### ISSUE THREAD

**Issue by jannejava** [Wulfheart/pretty-routes#31]
**Is your feature request related to a problem? Please describe.**

I have a big project with more than 50 controllers scattered around different packages. Sometimes I have a path but I want to find the controller and the method. 

Now I use route:pretty to get the route name and then search for the route’s name in the router.php to find the controller and method. 

**Describe the solution you'd like**

An option to display the controller’s class name and method instead of the name. 

**Describe alternatives you've considered**

Using route:list but it’s not possible to see all routes since I cannot scroll to the top of the list. Also it’s hard to read when the app I complex. 

Thanks for creating this package. I still find this 100% more useful than artisan route:list!

**System (please complete the following information):**
 - OS: [e.g. macOS, Manjaro Linux, Windows 10]
 - PHP Version: [e.g. 8.0.3]]
 - Package Version from the lock-file: [e.g. 0.2.2]
 - Laravel Version from the lock-file: [e.g. 8.5.2]
 - Shell: [e.g. Powershell, cmd, bash, zsh]
 - 
 macOS. Php 8.0.3. Zsh.

**Comment by Wulfheart** [comment]
Hey, thanks for submitting this feature request.
I could imagine an option where you can customize to display the the middleware or the controller. However, they are quite long and therefore don't align so well. Maybe [route:menu](https://github.com/morrislaptop/laravel-route-menu) is the right command for you.
Related to #33.

**Comment by Wulfheart** [comment]
Closing this for now as I think the `route:menu` command could be the thing you are looking for. Feel free to reopen if this is not the case.

**Comment by jannejava** [comment]
No worries! I have around 300 routes in my project to `route:menu` is not my cup of tea, I cannot scroll to the top of the list. ;-) 

However, for everyone like me looking to see Controllers: this exactly what I am looking for even if it's not a console command: https://github.com/andrey-helldar/pretty-routes

**Comment by Wulfheart** [comment]
This package also has the ability to search and may be better for your usecase.
