### ISSUE TITLE
Change path grep syntax to match Laravel

### ISSUE THREAD

**Issue by mattstauffer** [Wulfheart/pretty-routes#32]
Taylor just informed me that Laravel recently got except-path and has had only-path for a while, so it would probably be worth deprecating the old syntax and changing this package's flags to match Laravel's:

https://twitter.com/stauffermatt/status/1389245939106390019

<img width="1212" alt="image" src="https://user-images.githubusercontent.com/151829/116899732-ec0cae00-ac05-11eb-9e89-b9d268cbae5c.png">

Would you accept a PR to change the syntax and either drop the old syntax, or offer it as a deprecated fallback?

**Comment by Gummibeer** [comment]
Should we change the "name" flags as well in that case? 🤔
`--name` and `--except-name`

**Comment by Wulfheart** [comment]
@Gummibeer sure. For consistency. 

@mattstauffer of course. If you can’t make it in the next few days I could also do it myself.

**Comment by Gummibeer** [comment]
The only fear I have with these namings is conflicts. But would also match my idea of `--group-by` and `--group` options.

**Comment by Wulfheart** [comment]
`group` and `group-by` would mean two really different things. If I understand your proposal correctly, you'd like to have a `group` option for the type of the route, e.g. web or api. I'm wary to have two so similar options. 🤔

**Comment by Gummibeer** [comment]
No, the `--group` would be like `--name=user/*`.

So it would filter by group name. A filter name matches every route containing "user". But `--group` would match only routes starting with given string.

**Comment by Wulfheart** [comment]
Will upgrade it when Laravel 9 is released.

**Comment by Wulfheart** [comment]
Closing as the Laravel 9 will support the command natively as per [this PR](https://github.com/laravel/framework/pull/40269).

**Comment by baselrabia** [comment]
@Wulfheart what happens are they using your package or do they write it again from scratch and added it to Laravel 9

**Comment by Wulfheart** [comment]
As far as I can see did they write it from scratch but stated in the PR that it is inspired by this package (which is inspired by many other packages itself) but they enhanced it quite a lot and I'm really happy about it as it relieves me of the maintenance burden. 😍

**Comment by baselrabia** [comment]
Yeah, it's pretty cool that they did it, but you also did a great job here too 😉💪💪💪

**Comment by Wulfheart** [comment]
Thanks!
