### ISSUE TITLE
Add option to see middlewares in pretty

### ISSUE THREAD

**Issue by LeonBuchner** [Wulfheart/pretty-routes#33]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
It would be nice to have an option to see the middlewares for a route in pretty. 

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by Gummibeer** [comment]
Any idea how that should happen? I could only imagine a `route:inspect` command or some of the CLI interactivity to open/collapse a more detailed block per route. 🤔

**Comment by LeonBuchner** [comment]
Something like `route:pretty -m` or `route:pretty -middlewares` would be nice 
Also flags for controller actions would be nice (i saw it in another feature request here)

This could be  `route:pretty -c` or  `route:pretty -controllers`

**Comment by Gummibeer** [comment]
I meant how they should be displayed to be pretty.
Controllers is easy as it's a single string.
But middlewares are an array of strings - so multiline.
That would make the output not pretty anymore and same unreadable as the original command.
That's why I had the pretty complex interactive output in mind or a dedicated command to inspect a single route (possibly another package).

**Comment by LeonBuchner** [comment]
For me personally the only important section in the middleware array is the last one. 
For example: `App\Http\Middleware\RedirectIfAuthenticated` 
Should only be: `RedirectIfAuthenticated`     

I know what this middleware does and I dont need the exact path.

Displaying one middleware per line and it should be perfectly readable or a straight pipe like GET|HEAD

Global Default middlewares like `EncryptCookies` may have another color if possible

So I can see directly if my middlewares are correct.

**Comment by Wulfheart** [comment]
> Any idea how that should happen? I could only imagine a `route:inspect` command or some of the CLI interactivity to open/collapse a more detailed block per route. thinking

Do you mean maybe [this](https://github.com/morrislaptop/laravel-route-menu) package?

**Comment by Wulfheart** [comment]
Closed due to inactivity.
