### ISSUE TITLE
Package wulfheart/pretty_routes has a PHP requirement incompatible with your PHP version, PHP extensions and Composer version

### ISSUE THREAD

**Issue by johnef** [Wulfheart/pretty-routes#34]
PHP version 7.4
Composer version 2.0.7

**Describe the bug**
Try to install get ` Package wulfheart/pretty_routes has a PHP requirement incompatible with your PHP version, PHP extensions and Composer version`

**To Reproduce**
Try to install get

**Comment by Wulfheart** [comment]
There are some information missing:
```
**To Reproduce**
Steps to reproduce the behavior:
1. php artisan route:pretty --options`

**System (please complete the following information):**
 - OS: [e.g. macOS, Manjaro Linux, Windows 10]
 - PHP Version: [e.g. 8.0.3]]
 - Package Version from the lock-file: [e.g. 0.2.2]
 - Laravel Version from the lock-file: [e.g. 8.5.2]
 - Shell: [e.g. Powershell, cmd, bash, zsh]

```

**Comment by johnef** [comment]
**To Reproduce**
Steps to reproduce the behavior:
1. php artisan route:pretty --options` => I have not install the package yet.

**System (please complete the following information):**
 - OS: Windows 10
 - PHP : 7.3.12
 - Package Version from the lock-file: I have required the latest version (0.3.0)
 - Laravel Version from the lock-file: 8.12
 - Shell:  cmd

**Comment by Wulfheart** [comment]
Pretty Routes has a minimum requirement of PHP 7.4. Upgrade your php version to use it.
