### ISSUE TITLE
Not compatible with Laravel 7

### ISSUE THREAD

**Issue by MarkLester10** [Wulfheart/pretty-routes#35]
When I try to install it on my Laravel 7 project it shows this problem

 Problem 1
    - Root composer.json requires wulfheart/pretty_routes ^0.3.0 -> satisfiable by wulfheart/pretty_routes[0.3.0].
    - wulfheart/pretty_routes 0.3.0 requires illuminate/contracts ^8.0 -> found illuminate/contracts[v8.0.0, ..., 8.x-dev] but these were not loaded, likely because it conflicts with another require.

**Comment by Wulfheart** [comment]
What Laravel version do you use exactly?
Do you maybe have a repo with a Laravel 7 app I can try out?

**Comment by MarkLester10** [comment]
> What Laravel version do you use exactly?
> Do you maybe have a repo with a Laravel 7 app I can try out?

Yes I have several Laravel 7 in my public repo you can test in any of those projects

**Comment by bhushan** [comment]
Looks like we need to downgrade illuminate/contract but @Wulfheart for which version onwards you are planning to support ? Laravel 6 onwards on 7 onwards ? Imo we should support from LTS versions .. and keep it same with how laravel changes its LTS versions

**Comment by Wulfheart** [comment]
Update: As you might have guessed I don't plan to support Laravel 7 not much longer. Guess I will drop it when L9 is released.
