### ISSUE TITLE
Error after install package in Laravel 8

### ISSUE THREAD

**Issue by alowisiustri** [Wulfheart/pretty-routes#37]
```
ParseError
syntax error, unexpected 'Package' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST)

::Composer\Autoload\includeFile
E:\wamp64\www\AcodePlus\vendor\spatie\laravel-package-tools\src\PackageServiceProvider.php:14

`<?php

 

namespace Spatie\LaravelPackageTools;

 

use Carbon\Carbon;

use Illuminate\Support\Facades\View;

use Illuminate\Support\ServiceProvider;

use Illuminate\Support\Str;

use ReflectionClass;

use Spatie\LaravelPackageTools\Exceptions\InvalidPackage;

 

abstract class PackageServiceProvider extends ServiceProvider

{

    protected Package $package;   <-- error here (line 14)
 

    abstract public function configurePackage(Package $package): void;

 

    public function register()

    {

        $this->registeringPackage();

 

        $this->package = new Package();

 

        $this->package->setBasePath($this->getPackageBaseDir());

 

        $this->configurePackage($this->package);

 

        if (empty($this->package->name)) {

            throw InvalidPackage::nameIsRequired();

        }`

**Comment by Wulfheart** [comment]
Are you sure that it is related to this package? Could you verify it by trying to install another package? 
Do you have a repo to reproduce?

**Comment by alowisiustri** [comment]
After I remove this pretty route package, everything is okay.  I install it in the fresh project of laravel 8, same problem. I don't know what wrong. I install dompdf, datatable yajra, everything okay.

**Comment by Gummibeer** [comment]
On which PHP version are you running the application? And does the error happen during install or with the first web request?

**Comment by alowisiustri** [comment]
I use PHP version 7.4.9. 
There was no problem in instalation process. I can do php artisan route:pretty and give me pretty route view. But when I open my project in chrome browser (I use wamp server), there was an error above. Then I remove this package and my project back, no problem anymore. So I thought might be the problem in the package, but I'am not sure.

**Comment by Wulfheart** [comment]
I don't use wamp and don't have php7.4 installed on my machine. Therefore I can't reproduce it. 
Would you mind trying to install `composer require wulfheart/laravel-actions-ide-helper` and run your application. I expect your error to happen again as it seems to be related to the package registration and that package uses the same package.

**Comment by Wulfheart** [comment]
Just had another look at the snippet you posted. The line `syntax error, unexpected 'Package' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST)` suggests that PHP is unable to deal with the property type. Please ensure that you are at least running PHP7.4 and post the contents of `phpinfo()`. Furthermore, it would help me a lot if you would share a link to a repo so I can have a look at it and try it out.

**Comment by alowisiustri** [comment]
> I don't use wamp and don't have php7.4 installed on my machine. Therefore I can't reproduce it.
> Would you mind trying to install `composer require wulfheart/laravel-actions-ide-helper` and run your application. I expect your error to happen again as it seems to be related to the package registration and that package uses the same package.

Hi Alex,

Sorry for misinformation. I install PHP 7.4.9 but use PHP 7.3.2.1 in my Wamp server. I will try to install that package. I will give you more information after I install it.

Thanks.

**Comment by alowisiustri** [comment]
This is my observation,

I install your package "composer require wulfheart/pretty_routes" and running the project with "php artisan serve" and there is no problem, everything ok. And then I change to use WAMP server and use PHP 7.3.2.1 and the problem exist. After that, I change PHP version in my WAMP server to PHP 7.4.9, and there is no problem anymore. 
I thought this package not compatible with PHP 7.3.2.1, but I don't know, I still newbie here.

But thanks for your help. Your package help me a lot and I like the view of my route list.

**Comment by Wulfheart** [comment]
No problem. Glad it worked for you.
