### ISSUE TITLE
group by domain

### ISSUE THREAD

**Issue by donakhseputa** [Wulfheart/pretty-routes#39]
I have using Laravel with a multi subdomains, e.g.
- mydomain.tld as frontend
- admin.mydomain.tld as backend
- api.mydomain.tld as API

I configure them from `App\Providers\RouteServiceProvider`
can I use your package to show all routes grouped by domain?
thanks.

**Comment by Wulfheart** [comment]
Did you try —group=url?

**Comment by donakhseputa** [comment]
`php artisan route:pretty --group=url`
Grouping mode must be 'path' or 'name'.

still not work.

**Comment by Wulfheart** [comment]
Ah. Then it isn't supported.
